### ISSUE TITLE
Refactor: Update settings in browser storage via SettingsContext

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1285]
### Description

With the SettingsContext provided with this PR
- https://github.com/getAlby/lightning-browser-extension/pull/1177

the settings handling with browser.storage can be moved completely to this SettingsContext.

### Goal 
The Settings Context should be the only place for getting and updating the settings in/from browser.storage on component level

### TODO
- [ ] find all places where on Component Level settings are read and updated with `api.get/setSetting`
- [ ] replace reading and updating Settings with the hook `useSettings`
- [ ] ensure SettingsContext is updating browser.storage on every settings change accordingly
