### ISSUE TITLE
Extend LND connector with requestMethod

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1725]
### Feature description

With this pull request https://github.com/getAlby/lightning-browser-extension/pull/1724
it is possible to extend a connector with the method `requestMethod` which enables any Client to pass methods to the Connector's API other than explicitly provided by WebLN.

Right now it is only possible to extend the LND connector as a detailed REST API exists which can be easily integrated.
=> see their docs https://api.lightning.community/#lnd-rest-api-reference

## EXAMPLE

1. Extend the LND connector with

```TS
 async requestMethod(
    method: string,
    params?: Record<string, unknown>
  ): Promise<{ data: unknown }> {
    return this.request("GET", `/v1/${method}`, params, {}).then((response) => {
      return { data: response };
    });
  }
```

2. Connect with your LND account
3. In browser console type
```TS
 await window.webln.enable();
 await window.webln.request("getinfo");
```
4. Log the response

## Problem

From the code example above it would be only possible to send a GET request to the version1 of the lightning API.
The idea is to support not only GET but also POST requests and support different API versions.

## TODO

- [ ] go over the API docs and make a list of the first methods which should definitely be supported by WebLN
- [ ] discuss with the team this list
- [ ] in the connector create a mapping for these methods (see example code below)

### EXAMPLE

```ts
const apiMethodMap = {
  getinfo: {
    method: "GET",
    version: "v1"
  },
  "chainnotifier/register/blocks": {
    method: "POST",
    version: "v2"
  },
  .....
}

 // ....

 async requestMethod(
    method: string,
    params?: Record<string, unknown>
  ): Promise<{ data: unknown }> {
    return this.request(apiMethodMap[method].method, `/${apiMethodMap[method].version}/${method}`, params, {}).then((response) => {
      return { data: response };
    });
  }
```

### Describe alternatives

- Support only GET request for the first implementation?
- Support only API v1 for the first implementation?

### Additional context

Related to ticket https://github.com/getAlby/lightning-browser-extension/issues/1717
