### ISSUE TITLE
Permissions: User should be able to update or delete

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1726]
### Feature description

This pull request https://github.com/getAlby/lightning-browser-extension/pull/1724
extended the DB with the table "permissions".

The user can explicitly decide if a request should always be allowed for a host/allowance.
If so => this request method is saved within the DB
If not => the user is prompted every time again

Now, several permissions can be saved within the DB.
The user should be able to see all these permissions she once allowed the extension to save in order to edit or delete them.

## TODO
- [ ] build a UI to show all permissions for a specific host/allowance (design needed?)
- [ ] add an action to "list" all permissions for a host/allowance
- [ ] add an action to update an existing permission (=> extend the action "addPermission" from [PR](https://github.com/getAlby/lightning-browser-extension/pull/1724))
- [ ] add an action to delete a permission (=> action "deletePermission" already exists in [PR](https://github.com/getAlby/lightning-browser-extension/pull/1724) )

### Describe alternatives

---

**Comment by lisabaut** [comment]
Duplicated by https://github.com/getAlby/lightning-browser-extension/issues/1820

Closing
