### ISSUE TITLE
Nostr: Read and write request permission from DB

### ISSUE THREAD

**Issue by lisabaut** [getAlby/lightning-browser-extension#1727]
### Feature description

This pull request https://github.com/getAlby/lightning-browser-extension/pull/1724
extended the DB with the table "permissions".

Now, it is possible to get, add, delete a permission for a specific host/allowance.
The integration of Nostr enables two methods at the moment:
- ConfirmSignMessage
- ConfirmGetPublicKey

Both methods can now be saved in the DB (if the user decides to save them in order to be not asked again).

### TODO
- [ ] extend ConfirmSignMessage with checking first if the permission for this request exists, save this permission otherwise
- [ ] do the same for ConfirmGetPublicKey
- [ ] decide if this flow should happen within the Prompt or within the background script

### Describe alternatives

...
