### ISSUE TITLE
💵 Explore fiat-denominated accounts

### ISSUE THREAD

**Issue by reneaaron** [getAlby/lightning-browser-extension#1742]
### Feature description

More and more services are offering fiat denominated accounts via synthetic assets:
 - [kollider](https://kollider.xyz)
 - [galoy](https://galoy.io/)

![image](https://user-images.githubusercontent.com/100827540/201083946-13680767-6821-480d-bd6e-a6ab02d1e452.png)

Those services often offer multiple balances to their users. In Kollider's case it's: 
 - Bitcoin
 - synthetic USD 
 - synthetic EUR

We want to explore how this can be integrated into Alby by creating a connector for Kollider. (see WIP branch linked to this issue)

### Context
When connecting a Kollider account () a user would need to choose which balance should be used within Alby, it's currently out of scope to support multiple balances.

A connector would need to signal the current currency to the extension.

### Questions
 - What changes are needed in order for Alby to work with fiat-denominated accounts?
   - Receive & send screens
   - Balance in Account selector
   - Fiat currency conversion in transaction lists
   - Fiat inputs

### Useful links
 - [Kollider LNDHubx](https://lndhubx.kollider.xyz/)

### Out of scope
 - Having multiple balances in one account

### ToDo

- [ ] Link to registration page (where the user gets the credentials)

**Comment by bumi** [comment]
In the first step what we imo need to look at is how we can let the connector decide what currency the return amounts have. 
E.g. when we show the account balance we have a hard coded "sats" there. this would need to be the currency of the connector. 
Same in the incoming invoices. 
I'd also say if the currency is not btc/sats then we do not show any other fiat amount (or we show the sats amount, whatever is easier) 

in the outgoing payments list I'd still try to store sats amounts.

**Comment by lisabaut** [comment]
## First Implementation

- [ ] Create new connector "Kollider"
- [ ] add new connector to Websites screen
- [ ] when user creates Kollider => prompt user with "Which balance/account you want to add"
- [ ] either store this base currency in Settings (TBD)
- [ ] and/or add method to connector "getBaseCurrency" (TBD)
- [ ] Decision: No convertion will happen at any place, just do not show fiat at all

**Comment by bumi** [comment]
just for completeness: 
Here is the code where I explored Kollider: https://github.com/getAlby/lightning-browser-extension/pull/1770 

there does not need to be a special prompt, just like other connectors need some information this needs a "currency": 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/318/203077529-79c890f0-a4ab-4c76-a0bf-3859d42dd2fd.png">

I would also call it just `getCurrency` - because those accounts will only have one currency I guess.

and in the first step I'd only do all this in the account menu thing. 
The outgoing payments are stored locally and are not per connector, there we only have the sats amounts (we don't even know the actual fiat amount that was paid from that account then)

And then we also can show the sats amount in the incoming invoices I guess.

All inputs an webln calls stay in sats.
