### ISSUE TITLE
[Feature] Add Alby connector

### ISSUE THREAD

**Issue by rolznz** [getAlby/lightning-browser-extension#1956]
### Feature description

Currently we are using the lndhub connector for hosted Alby accounts as well as other lndhub connections such as Bluewallet. There is no reliable way to determine whether the lndhub connection is an Alby hosted account or a connection to some other node (only option is checking the account alias or connector config url, which could both change). Also, it limits the possibilities of what we can support since we need to be compatible with the lndhub API. If we create an Alby connector, we can use the Alby OAuth API.

### Describe the solution

Create a new "Alby" connector and start using it for new user accounts. Consider whether a migration is needed in the future or we can keep existing accounts using the lndhub connector.

**TODO**
 - [ ] Create a new Alby connector (copy LNDHub) 
 - [ ] Refactor `isAlby()` to use the account type
 - [ ] Migrate all existing LNDHub accounts (check for the lndhub url (ln.getalby.com))

### Additional context

From the discussion on how to determine whether or not the connection is an Alby hosted wallet or not: https://github.com/getAlby/lightning-browser-extension/pull/1892

### What does this enable?
- Show lightning address on receive tab
- Add link to alby account in the extension connector UI
- Add extra metadata in invoices and transactions (available from the Alby backend)
- Using an Alby API rather than the LndHub API

### Are you working on this?

None
